import React from "react";
import Link from "next/link";
import Image from "next/image";
import alvi_image from "@/public/images/Ahmad Fahmid.jpg";

export const metadata = {
  title: "Blog page",
  description: "Generated by create next app",
};

const blogs = [
  { id: 1, title: "Blog 1", content: "This is my first blog" },
  { id: 2, title: "Blog 2", content: "This is my second blog" },
  { id: 3, title: "Blog 3", content: "This is my third blog" },
];

export default function blogspage() {
  return (
    <div>
      <ul>
        {blogs.map((i) => {
          return <Blogtittle key={i.id} title={i.title} id={i.id} />;
        })}
      </ul>
      <div className="w-[400px]">
        <Image placeholder="blur" src={alvi_image} alt="Alvi" />
      </div>
    </div>
  );
}

function Blogtittle({ title, id }) {
  return (
    <li>
      <Link href={`blogs/${id}`}>{title}</Link>
    </li>
  );
}
