import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="p-10">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="mb-10">
          <Link href="/">HOME</Link> | <Link href="/about">ABOUT</Link> |{" "}
          <Link href="/blogs">Blogs</Link> | <Link href="/posts">posts</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
